name: casino_test
description: Casino test application

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.13.4 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  cached_network_image: ^3.2.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  fluttertoast: ^8.0.9
  freezed_annotation: ^2.0.1
  get_it: ^7.2.0
  http: ^0.13.4
  internet_connection_checker: ^0.0.1+3
  json_annotation: ^4.4.0
  provider: ^6.0.2
  timeago: ^3.2.2

dev_dependencies:
  build_runner: ^2.0.0
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.0.2
  json_serializable: ^6.0.0

flutter:
  uses-material-design: true
